<?php
/**
 * Android Forensic Tool - Export Report API
 * Generates PDF/HTML forensic report
 */
header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');

require_once '../includes/config.php';

$response = [
    'success' => false,
    'filename' => null,
    'downloadUrl' => null,
    'error' => null
];

// Get export options
$input = json_decode(file_get_contents('php://input'), true) ?? [];
$format = $input['format'] ?? 'html';
$includeLogcat = $input['includeLogcat'] ?? true;
$includeSms = $input['includeSms'] ?? true;
$includeCalls = $input['includeCalls'] ?? true;
$includeLocation = $input['includeLocation'] ?? true;

$logsPath = getLogsPath();
$exportPath = dirname($logsPath) . '/exports';

// Create exports directory if not exists
if (!is_dir($exportPath)) {
    mkdir($exportPath, 0755, true);
}

try {
    // Call Python reporting script
    $pythonPath = PYTHON_PATH;

    // Execute Python script to generate report
    // Change directory to root so imports work
    $rootDir = dirname(dirname(__DIR__));
    $command = "cd /d \"$rootDir\" && $pythonPath -c \"from reporting import export_full_report; export_full_report()\" 2>&1";
    $output = [];
    $returnCode = 0;

    exec($command, $output, $returnCode);

    if ($returnCode !== 0) {
        throw new Exception("Python script failed: " . implode("\n", $output));
    }

    // Find the most recent report file
    $exportPath = dirname($logsPath) . '/exports';
    if (!is_dir($exportPath)) {
        throw new Exception("Exports directory not found");
    }

    $files = glob($exportPath . '/forensic_report_*.html');
    if (empty($files)) {
        throw new Exception("No report file generated");
    }

    // Get the most recent file
    usort($files, function ($a, $b) {
        return filemtime($b) - filemtime($a);
    });

    $latestFile = $files[0];
    $filename = basename($latestFile);

    $response['success'] = true;
    $response['filename'] = $filename;
    $response['downloadUrl'] = "../exports/" . $filename;
    $response['message'] = "Forensic report generated successfully!";
    $response['output'] = implode("\n", $output);

} catch (Exception $e) {
    $response['error'] = $e->getMessage();
}

echo json_encode($response);

/**
 * Generate HTML Report
 */
function generateHtmlReport($data)
{
    $html = <<<HTML
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Android Forensic Report</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', Arial, sans-serif; line-height: 1.6; color: #333; background: #f5f5f5; }
        .container { max-width: 1200px; margin: 0 auto; padding: 20px; }
        .header { background: linear-gradient(135deg, #1e3c72, #2a5298); color: white; padding: 40px; text-align: center; margin-bottom: 30px; border-radius: 10px; }
        .header h1 { font-size: 2.5rem; margin-bottom: 10px; }
        .header p { opacity: 0.9; }
        .section { background: white; border-radius: 10px; padding: 25px; margin-bottom: 20px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        .section h2 { color: #1e3c72; border-bottom: 2px solid #2a5298; padding-bottom: 10px; margin-bottom: 20px; }
        .stat-box { display: inline-block; background: #f0f4f8; padding: 15px 25px; border-radius: 8px; margin-right: 15px; margin-bottom: 10px; }
        .stat-box .value { font-size: 2rem; font-weight: bold; color: #1e3c72; }
        .stat-box .label { font-size: 0.9rem; color: #666; }
        .log-preview { background: #0d1117; color: #c9d1d9; padding: 15px; border-radius: 5px; font-family: monospace; font-size: 0.85rem; overflow-x: auto; max-height: 400px; overflow-y: auto; white-space: pre-wrap; }
        .footer { text-align: center; padding: 20px; color: #666; font-size: 0.9rem; }
        @media print { body { background: white; } .section { box-shadow: none; border: 1px solid #ddd; } }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🔍 Android Forensic Report</h1>
            <p>Generated: {$data['generated']}</p>
        </div>
HTML;

    foreach ($data['sections'] as $key => $section) {
        $html .= <<<HTML
        <div class="section">
            <h2>{$section['title']}</h2>
            <div class="stat-box">
                <div class="value">{$section['count']}</div>
                <div class="label">Total Records</div>
            </div>
            <h4 style="margin-top: 20px; margin-bottom: 10px;">Sample Data:</h4>
            <div class="log-preview">{$section['sample']}</div>
        </div>
HTML;
    }

    $html .= <<<HTML
        <div class="footer">
            <p>This report was generated by Android Forensic Tool</p>
            <p>© 2024 - For authorized forensic use only</p>
        </div>
    </div>
</body>
</html>
HTML;

    return $html;
}
